# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    name: test suite
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app && /usr/bin/xcodebuild -version
    - name: Build and run iOS
      run: xcodebuild test -scheme KuwaharaFilter -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0.1' | xcpretty && exit ${PIPESTATUS[0]}
    - name: Build macOS
      run: swift build
    - name: run macOS
      run: swift test
